repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-yapf
    rev: v0.21.0
    hooks:
    -   id: yapf
        args:
         - -p
         - -i
         - -r
-   repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.2
    hooks:
    - id: go-fmt
