download:
	wget http://s3.climb.ac.uk/nanopore/Ecoli_MinKNOW_1.4_RAD002_Sambrook.tar
ref:
	wget 'https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&save=file&log$=seqview&db=nuccore&report=fasta&id=1356591284&extrafeat=976&conwithfeat=on&hide-sequence=on' -O ref.fasta
